# install-services.yml
---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Install apache
        yum: name=httpd state=latest
      - name: Ensure apache starts
        service:
          name: httpd
          state: started
          enabled: yes

  - hosts: webservers
    become: true
    tasks:
      - name: Get NodeJS Installer
        get_url: 
          url: https://rpm.nodesource.com/setup_10.x
          dest: /tmp/nodejs.sh
          mode: 600
      - name: Execute NodeJS script
        shell: /tmp/nodejs.sh
      - name: Install services
        yum:
          name:
            - httpd
            - nodejs
          state: latest
      - name: Install angular-cli
        npm: 
          name: "@angular/cli"
          global: yes
      - name: Ensure apache starts
        service:
          name: httpd
          state: started
          enabled: yes